### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by lonestar125** [ErynGalen/nw-rpi-guide#1]
For the 2nd method:
"2, alternative) Any Raspberry Pi 2/3/4/0 on Linux | N0110 >= E16"

the title indicates >=E16 but the requirements indicate <E16:

"
Requirements:
Numworks Calculator N0100 or N0110 with Epsilon Firmware < 16
"

which one is correct?

**Comment by ErynGalen** [comment]
Oops indeed it's >= E16 which is correct.
